### ISSUE TITLE
Change directory where gollum searches for grids

### ISSUE THREAD

**Issue by rhdtownsend** [BrownDwarf/gollum#110]
Is there a way to change where gollum searches for grid data? If it is hardwired to ~/libraries/raw, that should be user-changeable.

Review link: https://github.com/openjournals/joss-reviews/issues/6601

**Comment by DanielAndreasen** [comment]
Hi @rhdtownsend, I think this is related to #105.

**Comment by Sujay-Shankar** [comment]
Hi all, I believe the most recent commit has finished up the path issue, gollum now automatically creates your config with default paths if it doesn't detect one (located in gollum's source directory, all you have to do to kick off this auto-creation is import PrecomputedSpectrum, or any module that subclasses it such as PHOENIX or Sonora), and this config file can be changed to a new user default without further git stuff overwriting it. If there is anything here that wasn't mentioned in #105 , do let me know, otherwise we should be good to close this one.

**Comment by Sujay-Shankar** [comment]
I also will be adding instructions regarding the config system to the documentation when I get around to editing that.
