### ISSUE TITLE
PHOENIXSpectrum 

### ISSUE THREAD

**Issue by fredifqh** [BrownDwarf/gollum#121]
I get the following error: 

URLError: <urlopen error ftp error: URLError("ftp error: error_perm('550 lte07500-4.50-0.0.PHOENIX-ACES-AGSS-COND-2011-HiRes.fits: No such file or directory')")>

after apply:

`s = PHOENIXSpectrum(teff=7500, logg=4.5, wl_lo= 5000, wl_hi=7000, download=True)`

**Comment by Sujay-Shankar** [comment]
Hi there! This error is due to the sampling of the PHOENIX grid in Teff space. From 2300K to 7000K, the grid is sampled in 100K increments, but from 7000K to 12000K, the grid sampling changes to 200K increments. This means that there are models for 7400K and models for 7600K, but not for 7500K as we do not yet support model grid interpolation.
