### ISSUE TITLE
Should we allow automatic grid downloading with the `download=` approach?

### ISSUE THREAD

**Issue by gully** [BrownDwarf/gollum#52]
Currently we allow the downloading of a single PHOENIX model with the `download=` kwarg.  Hypothetically we could extend this into the `PHOENIXGrid`.  The problem is that it would take a long time to download everything if the grid is huge (15G).

This approach *does* do caching though, so maybe it's OK?  

Thoughts?

**Comment by SujayShankarUT** [comment]
`download = True` has been enabled with PHOENIXGrid objects. The initial grid is indeed large, so the first download of the full grid will be a "let this run for a few hours" scenario, but subsequent grid creations are always subsets of the full grid, meaning they'll always lie in cache. Expansion of the parameter ranges results in the entire grid needing to reload, so it's recommended that this downloading route be used on the full grid so that the cache never has to reload again. 
The other part of this is with the filenames and directory structure that a local download has that astropy cache lacks, but that part is encapsulated in #83 . Therefore, we close out this one.
